### ISSUE TITLE
Duplicate Plugins for Flutter Boom Menu

### ISSUE THREAD

**Issue by Mohanraj153** [RegNex/boom_menu#1]
Hi,
This is illegal to duplicate plugin uploaded. so you remove this plugin from pub.dev. otherwise i'll raise the complain to block your account from Pub.dev.

Note: 
The Original Plugin for Name & Page,
https://pub.dev/packages/flutter_boom_menu

**Comment by iamEtornam** [comment]
Thank you for your message. I have been contacted by a representative from Google on the pub.dev team. I have responded to their email. I believe the issue will be addressed by them.
